function toggleTranslation(textId, buttonElement) {
    const textElement = document.getElementById(textId);
    const isEnglish = textElement.textContent.includes('Artificial Intelligence(AI)') || 
                      textElement.textContent.includes('Critical infrastructure security') || 
                      textElement.textContent.includes('Network security is the protection') || 
                      textElement.textContent.includes('Endpoint security refers to the protection') || 
                      textElement.textContent.includes('Application security') || 
                      textElement.textContent.includes('Cloud security involves protecting data') ||
                      textElement.textContent.includes('Information security') ||
                      textElement.textContent.includes('Mobile security');
    if (isEnglish) {
        // Translate to Myanmar
        switch(textId) {
            case 'text1':
                textElement.textContent = 'အတုအယောင် ထောက်လှမ်းရေး (AI) သည် ခြိမ်းခြောက်မှု ရှာဖွေတွေ့ရှိမှုကို တိုးမြှင့်ခြင်းဖြင့် လုံခြုံမှုကို တိုးတက်စေပြီး တုံ့ပြန်နိုင်စွမ်းများနှင့် အောက်ပါနည်းများဖြင့် ဆိုက်ဘာလုံခြုံရေး တိုင်းတာချက်များ– အဆင့်မြင့်ခြိမ်းခြောက်မှု ရှာဖွေတွေ့ရှိခြင်းနှင့် အချိန်မှန်စောင့်ကြည့်ခြင်း: AI သည် ထူးခြားသော ပုံစံများနှင့် အပြုအမူများအတွက် အချက်အလက်များကို ဆန်းစစ်ပြီး စောစောခြိမ်းခြောက်မှုကို ရှာဖွေတွေ့ရှိနိုင်သည်။ အေအိုင် လုံခြုံ ရေး သည် ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ မှ ဉာဏ်ရည်တု စနစ် များ ကို ကာကွယ် ရန် ရည်ရွယ် ထား သော ဆောင်ရွက် ချက် များ နှင့် အလေ့အကျင့် များ ကို ရည်ညွှန်း သည် ။ ယင်း တွင် အေအိုင် မော်ဒယ် များ နှင့် အချက်အလက် များ ကို အလွဲသုံးစား ပြု ခြင်း ၊ တိုက်ခိုက် မှု များ ၊ နှင့် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု များ မှ ကာကွယ် စောင့်ရှောက် ခြင်း ပါဝင် သည် ။ အဓိက စိုးရိမ် ပူပန် မှု များ တွင် အချက်အလက် လုံခြုံ ရေး သေချာ စေ ခြင်း ၊ ပုံစံ ကို ထိန်းချုပ် ခြင်း ၊ နှင့် ရန်ဘက် တိုက်ခိုက် မှု များ ကို ကာကွယ် ခြင်း တို့ ပါဝင် သည် ။ ဤ ခြုံငုံ သုံးသပ် ချက် သည် ဆိုင်ဘာ ဘေးကင်း လုံခြုံ ရေး တိုးတက် ရန် အေအိုင် အသုံးပြု ခြင်း ပါဝင် သော ၊ အေအိုင် လုံခြုံ ရေး ၏ သတ်မှတ် ချက် အပေါ် အာရုံစိုက် သည် ။ သို့သော်လည်း ၊ ၎င်း သည် အေအိုင် ၏ အလားအလာ ရှိ သော အားနည်းချက် များ နှင့် အေအိုင် စနစ် များ ကို ကာကွယ် ရန် အ ကောင်း ဆုံး အလေ့အကျင့် များ အပေါ် သတင်း အချက်အလက် များ လည်း ပါဝင် သည် ။ အသိဉာဏ်အတု (AI) သည် စက်မှုလုပ်ငန်းအမျိုးမျိုးကို တော်လှန်ရေး လုပ်ကိုင်ခဲ့ပြီး ဆိုင်ဘာဘေးကင်းရေးမှာလည်း ခြွင်းချက်မရှိပါ။ အေအိုင် လုံခြုံ ရေး ဖြေရှင်း ချက် များ သည် ယနေ့ ၏ ဒစ်ဂျစ်တယ် ရှုခင်း တွင် ဖြစ် နိုင် ချေ ရှိ သော ခြိမ်းခြောက် မှု များ ကို ဖော် ထုတ် ရန် နှင့် လျှော့ချ ခြင်း အတွက် အစွမ်းထက် သော ကိရိယာ များ အဖြစ် ပေါ် ထွက် လာ ခဲ့ သည် ။';
                break;
            case 'text2':
                textElement.textContent = 'အရေးကြီးသောအခြေခံအဆောက်အအုံ လုံခြုံ ရေး တွင် ဝန်ဆောင် မှု များ နှင့် သယ်ယူ ပို့ဆောင် ရေး ကွန်ယက် များ ကဲ့သို့ ၊ မရှိမဖြစ် လိုအပ် သော စနစ် များ နှင့် ပိုင်ဆိုင် မှု များ ကို ကာကွယ် စောင့်ရှောက် ခြင်း ပါဝင် သည် ၊ သူ တို့ ၏ အဆက်မပြတ် လုပ်ဆောင် မှု ကို သေချာ စေရန် နှင့် ပြည်သူ့ လုံခြုံ ရေး ကို ကာကွယ် ရန် ခြိမ်းခြောက် မှု များ မှ ပါဝင် သည် ။ အရေးကြီး သော အခြေခံ အဆောက်အအုံ လုံခြုံ ရေး တွင် အမျိုးသား လုံခြုံ ရေး ၊ စီးပွားရေး ၊ နှင့် ပြည်သူ့ လုံခြုံ ရေး အတွက် အရေးပါ သော မရှိမဖြစ် လိုအပ် သော စနစ် များ နှင့် ပိုင်ဆိုင် မှု များ ကို ကာကွယ် ခြင်း ပါဝင် သည် ။ အရေးပါသော အခြေခံအဆောက်အအုံများ လုံခြုံရေးသည် စွမ်းအင်၊ ရေနှင့် လိုက်နာမှုကဲ့သို့သော မရှိမဖြစ်လိုအပ်သောစနစ်များကို ကာကွယ်ပေးသည်။ လုံခြုံရေးထိန်းသိမ်းရေးအတွက် အရေးပါသည်။ ရည်ရွယ် ချက် မှာ ဤ အရေးကြီး သော ဝန်ဆောင် မှု များ လုပ်ဆောင် မှု နှင့် လုံခြုံ မှု ကို သေချာ စေရန် ဖြစ် သည် ။ စိုက်ပျိုးရေး၊ စွမ်းအင်၊ အစားအစာနှင့် သယ်ယူပို့ဆောင်ရေးကဲ့သို့သော စက်မှုလုပ်ငန်းများတွင် အဖွဲ့အစည်းများ၏ အရေးပါသော အခြေခံအဆောက်အအုံများသည် ဆိုက်ဘာခြိမ်းခြောက်မှုများ၊ သဘာဝဘေးအန္တရာယ်များနှင့် အကြမ်းဖက်ခြိမ်းခြောက်မှုများမှ ကာကွယ်မှုရရှိရန် သေချာစေသည်။ ဝင်ရောက်ကြည့်ရှုရေး ထိန်းချုပ်မှု– ခွင့်ပြုချက်မရတဲ့ အသုံးပြုသူတွေနဲ့ ကိရိယာတွေကို တားဆီးခြင်းက ကွန်ယက်ကို ဝင်ရောက်ကြည့်ရှုခြင်းမှ ကာကွယ်ခြင်း။  Application လုံခြုံရေး – လုံခြုံ ရေး ဆောင်ရွက် ချက် များ ကို ဖြစ် နိုင် ချေ ရှိ သော အားနည်းချက် များ ကို ပိတ်ဆို့ ရန် ဟာ့ဒ်ဝဲ နှင့် ဆော့ဖ်ဝဲလ် များ တွင် ထား ရှိ သည် ။ မီးရှူးမီးပန်းများ– ယာဉ်အသွားအလာကို ကွန်ရက်ထဲဝင်ခြင်း သို့မဟုတ် ထွက်ခွာခြင်းမှ တားဆီးနိုင်သည့် သို့မဟုတ် တားဆီးနိုင်သည့် ဂိတ်ကီပင်းကိရိယာများဖြစ်သည် ။';
                break;
            case 'text3':
                textElement.textContent = 'ကွန်ယက်လုံခြုံရေး ဆိုသည်မှာ အခြေခံကွန်ရက်အခြေခံအဆောက်အအုံကို ခွင့်ပြုမထားသော လှမ်းလာခြင်း၊ မဖြစ်သင့်သောအသုံးချခြင်း၊ သို့မဟုတ် ခိုးယူမှုမှ ကာကွယ်ပေးခြင်းဖြစ်သည်။ ဤသည်မှာ ကိရိယာများ၊ အက်ပ်လီကေးရှင်းများ၊ အသုံးပြုသူများနှင့် အက်ပ်လီကေးရှင်းများကို လုံခြုံစွာ လုပ်ဆောင်နိုင်ရန် အဆောက်အအုံတည်ဆောက်ခြင်းနှင့် ပတ်သက်ပြီးပါသည်။ Network security ဆိုသည်မှာ ကွန်ပျူတာကွန်ရက်နှင့် ၎င်း၏ဒေတာများကို ခွင့်ပြုမထားသော လှမ်းလာခြင်း၊ မဖြစ်သင့်သောအသုံးချခြင်း၊ နှင့် စက်မှုကျူးလွန်မှုများမှ ကာကွယ်ပေးခြင်းဖြစ်သည်။၎င်းတွင် ဖိုင်ဝေါ်များ၊ စာဝှက်ခြင်း၊ intrusion detection systems (IDS) နှင့် ကွန်ရက်ရင်းမြစ်များ၏ စိစစ်မှု၊ လျှို့ဝှက်မှု၊ နောက်ဆုံးအခြေအနေအတိုင်းရှိမှုတို့ကို သေချာစေရန် ပုံမှန်ကြီးကြပ်မှုတို့ကို လုပ်ဆောင်ပါသည်။ စက်မှုကျူးလွန်မှုများထပ်မံဖြစ်ပေါ်လာသောခေတ်တစ်ခေတ်တွင် ခိုင်မာသောကွန်ရက်လုံခြုံရေးသည် အရေးကြီးသောသတင်းအချက်အလက်များကို ကာကွယ်ရန်နှင့် ဒစ်ဂျစ်တယ်ဆက်သွယ်ရေးတွင် ယုံကြည်မှုကို ထိန်းသိမ်းထားရန် အရေးကြီးသည်။ ကွန်ယက် လုံခြုံ ရေး သည် သင် ၏ ကွန်ရက် နှင့် အချက်အလက် များ ကို ချိုးဖောက် မှု များ ၊ ဝင်ရောက် ဝင်ရောက် စွက်ဖက် မှု များ နှင့် အခြား ခြိမ်းခြောက် မှု များ မှ ကာကွယ် ပေး သည် ။ ၎င်း သည် ဟာ့ဒ်ဝဲ နှင့် ဆော့ဖ်ဝဲလ် ဖြေရှင်းနည်း များ အပြင် ကွန်ယက် အသုံးပြု မှု ၊ ဝင်ရောက် ကြည့်ရှု နိုင် မှု ၊ နှင့် ခြုံငုံ ခြိမ်းခြောက် မှု ကာကွယ်ရေး နှင့် ဆက်စပ် သော လုပ်ငန်းစဉ် များ သို့မဟုတ် စည်းမျဉ်း များ နှင့် ဖွဲ့စည်းပုံ များ ကို ဖော်ပြ သော ကြီးမား ကျယ်ပြန့် ပြီး အလွန် ကြီးမား သော အသုံးအနှုန်း တစ် ခု ဖြစ် သည် ။ ကွန်ယက် လုံခြုံ ရေး တွင် ထိန်းချုပ် မှု ၊ ဗိုင်းရပ်စ် နှင့် အန်တီဗိုင်းရပ်စ် ဆော့ဖ်ဝဲလ် ၊ application လုံခြုံ ရေး ၊ ကွန်ယက် ခွဲခြမ်းစိတ်ဖြာ မှု ၊ ကွန်ယက် နှင့် ဆက်စပ် သော လုံခြုံ ရေး အမျိုးအစား များ ( အဆုံးသတ် နေရာ ၊ ကြိုးမဲ့ဆက်သွယ်ရေး ၊ ဗီပီအန် လျှို့ဝှက် မှု နှင့် ပိုမို ပါဝင် သည် ။';
                break;
            case 'text4':
                textElement.textContent = 'အဆုံးသတ်လုံခြုံရေး ဆိုသည်မှာ ကွန်ရက်လမ်းကြောင်းများအတိုင်း ကွန်ပျူတာ၊ စမတ်ဖုန်းများနှင့် တက်ဘလက်များကဲ့သို့သော တစ်ဦးချင်းစီ၏ ကိရိယာများကို စက်မှုကျူးလွန်မှုများမှ ကာကွယ်ခြင်းဖြစ်သည်။ ဤကိရိယာများကို အန္တရာယ်ဖြစ်နိုင်မှုများနှင့် ခွင့်ပြုမထားသော လှမ်းလာမှုများမှ ကာကွယ်ရန် ဗိုင်းရပ်စ်ဘက်စုံကာကွယ်ရေးဆော့ဖ်ဝဲ၊ ဖိုင်ဝေါ်များနှင့် စာဝှက်ခြင်းကဲ့သို့သော လုံခြုံရေးအတိုင်းအတာများကို ပြုလုပ်ခြင်းဖြစ်သည်။ Endpoint security ဆိုသည်မှာ ကွန်ရက်သို့ ချိတ်ဆက်ထားသော ကွန်ပျူတာများ၊ စမတ်ဖုန်းများနှင့် တက်ဘလက်များကဲ့သို့သော ကိရိယာများကို ကာကွယ်ရန် လုံခြုံရေးအတိုင်းအတာများကို လုပ်ဆောင်ခြင်းဖြစ်သည်။ ကိရိယာများနှင့် ၎င်းတို့ချိတ်ဆက်ထားသောကွန်ရက်ကို ကာကွယ်ရန် ဗိုင်းရပ်စ်ဘက်စုံကာကွယ်ရေးဆော့ဖ်ဝဲ၊ ဖိုင်ဝေါ်များ၊ intrusion detection systems (IDS) နှင့် စာဝှက်ခြင်းကို လုံခြုံရေးဖြေရှင်းချက်များသည် လက်ရှိဖြစ်စဉ်ဖြစ်သည်။ ကိရိယာများကို လုံခြုံစေရန်အတွက် ရည်ရွယ်ချက်မှာ ကွန်ရက်၏လုံခြုံရေးဖြစ်ရပ်များကို လျော့နည်းစေခြင်းဖြစ်သည်။ အဆုံးသတ် ကာကွယ်ရေး စင်တာ ( အီးပီပီ ) သည် အခြား မလိုမုန်းထား သော လုပ်ဆောင် မှု များ အကြား ဖိုင် - အခြေပြု မားလ်ဝဲ တိုက်ခိုက် မှု များ ကဲ့သို့ လုံခြုံ ရေး ခြိမ်းခြောက် မှု များ ကို ဖော် ထုတ် ရန် နှင့် ကာကွယ် ရန် အသုံးပြု သော ဖြေရှင်း ချက် တစ် ခု ဖြစ် သည် ။ ၎င်း သည် ပြင်းထန် သော လုံခြုံ ရေး ဖြစ်ရပ် များ နှင့် သတိပေးချက် များ ကို တုံ့ပြန် ရန် လိုအပ် သော စုံစမ်း စစ်ဆေး မှု နှင့် ပြန်လည် ပြုပြင် ရေး စွမ်းရည် များ ကို လည်း ထောက်ပံ့ ပေး သည် ။';
                break;
            case 'text5':
                textElement.textContent = 'Application လုံခြုံရေးတွင် လျှောက်လွှာ များ ကို ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ မှ ကာကွယ် ရန် ရည်ရွယ် ထား သော တိုင်းတာ မှု များ နှင့် အလေ့အကျင့် များ ပါဝင် သည် ။  ၎င်း သည် ဆော့ဖ်ဝဲလ် နှင့် ၎င်း ၏ အချက်အလက် များ ကို ၎င်း ၏ သက်တမ်း တစ်လျှောက် လုံး လုံခြုံ ရေး အပေါ် အာရုံစိုက် ပြီး ၊ အပလီကေးရှင်း များ ကို တိုက်ခိုက် မှု များ နှင့် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု များ မှ ကာကွယ် ပေး ရန် သေချာ စေ သည် ။ Application လုံခြုံ ရေး တွင် ဆော့ဖ်ဝဲလ် ပရိုဂရိတ် များ ကို ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ မှ ကာကွယ် ခြင်း ပါဝင် သည် ။ ၎င်း တွင် တိုက်ခိုက် မှု များ မှ လျှောက်လွှာ လုံခြုံ မှု ရှိ စေရန် နှင့် ၎င်း ၏ သက်တမ်း တစ်လျှောက် လုံး ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု များ မှ လုံခြုံ မှု ရှိ စေရန် သေချာ စေရန် ကုဒ် သုံးသပ် မှု များ ၊ ထိုးဖောက် ခြင်း စမ်းသပ် ခြင်း ၊ နှင့် လုံခြုံ သော ကုဒ် လုပ်ထုံးလုပ်နည်း များ ပါဝင် သည် ။ လျှောက်လွှာ လုံခြုံ ရေး ၏ အဆုံးသတ် ရည်မှန်း ချက် မှာ တိုက်ခိုက် သူ များ ကို ထိခိုက်လွယ် သော သို့မဟုတ် ပိုင်ဆိုင် သော အချက်အလက် များ ကို ဖျက် ခြင်း မှ ကာကွယ် ရန် ဖြစ် သည် ။ အသုံးချမှုအများဆုံး လုံခြုံရေးအားနည်းချက်များကို လူသိများကြသည်။ အချိန်ကြာလာတာနဲ့အမျှ အဖွဲ့အစည်းအသီးသီးက ခြေရာခံကြတယ်။ အိုးပင်းဝက်ဘ်အပ္ပလီကေးရှင်း လုံခြုံရေး စီမံကိန်း (အိုးဒဗလျူအေအက်စ်ပီ) ထိပ်တန်း ဆယ်ခုစာရင်းနှင့် သာမန် အားနည်းချက်များ အန်ဒဗလျူအီး) ပေါင်းစပ်ပါသည်။ Application လုံခြုံ ရေး တွင် ဆော့ဖ်ဝဲလ် ပရိုဂရမ် များ ကို ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ မှ ကာကွယ် ခြင်း ပါဝင် ပြီး ခွင့်ပြု ချက် မ ရှိ သော အချက်အလက် ချိုးဖောက် မှု များ ၊ သို့မဟုတ် အခြား မလိုတမာ လုပ်ဆောင် မှု များ ကို ဦးတည် စေ နိုင် သည် ။ ၎င်း တွင် လုံခြုံ သော ကိုဒင်း ပြုလုပ် ခြင်း ၊ အားနည်းချက် များ အတွက် ပုံမှန် စမ်းသပ် ခြင်း ၊ စစ်ဆေး ခြင်း နှင့် ခွင့်ပြု ချက် စနစ် များ အကောင်အထည်ဖော် ခြင်း ၊ နှင့် ဆော့ဖ်ဝဲလ် အသစ် ပြင်ဆင် မှု များ ကို ထိန်းသိမ်း ခြင်း ကဲ့သို့ အလေ့အကျင့် များ ပါဝင် သည် ။';
                break;
            case 'text6':
                textElement.textContent = 'မိုးတိမ်လုံခြုံမှု တွင် အချက်အလက် များ ၊ application များ ၊ နှင့် ဝန်ဆောင် မှု များ ကို ကာကွယ် ခြင်း ပါဝင် သည် ။ ၎င်း တွင် လျှို့ဝှက် ချက် ၊ ဝင်ရောက် ကြည့်ရှု မှု ထိန်းချုပ် ခြင်း ၊ ပုံမှန် စောင့် ကြည့် ခြင်း စ သည့် ဆောင်ရွက် ချက် များ ပါဝင် ပြီး တိမ် - အခြေပြု အရင်းအမြစ် များ ရရှိ နိုင် မှု ကို သေချာ စေရန် လျှို့ဝှက် ချက် ၊ အစုလိုက်အပြုံလိုက် လုံခြုံ ရေး တွင် အချက်အလက် များ ၊ ပရိုဂရမ် များ ၊ နှင့် အခြေခံ အဆောက်အအုံ များ ကို ကာကွယ် ရန် အကောင်အထည်ဖော် ထား သော မူဝါဒ များ ၊ နည်းပညာ များ ၊ နှင့် ထိန်းချုပ် မှု များ ပါဝင် သည် ။ ၎င်း သည် ခွင့်ပြုချက် မ ရှိ သော အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် အခြား ဆိုက်ဘာ ခြိမ်းခြောက် မှု များ မှ ကာကွယ် ခြင်း အားဖြင့် အချက်အလက် လုံခြုံ မှု ၊ သမာဓိ နှင့် ရရှိ နိုင် မှု ကို သေချာ စေရန် အာရုံစိုက် သည် ။ အဓိက ကဏ္ဍ များ တွင် အချက်အလက် လျှို့ဝှက် ခြင်း ၊ ကိုယ်ရေးကိုယ်တာ နှင့် ဝင်ရောက် ကြည့်ရှု မှု စီမံ ခန့်ခွဲ ခြင်း ၊ စည်းမျဉ်း များ ကို လိုက်နာ ခြင်း ၊ ကွန်ယက် လုံခြုံ ရေး ၊ နှင့် ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ အတွက် စောင့် ကြည့် ခြင်း တို့ ပါဝင် သည် ။ Cloud security တွင် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု ၊ အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် ဆိုက်ဘာ တိုက်ခိုက် မှု များ ကဲ့သို့ ခြိမ်းခြောက် မှု များ မှ တိမ် ပတ်ဝန်းကျင် တွင် သိမ်းဆည်း ထား သော အချက်အလက် များ ၊ ပရိုဂရမ် များ ၊ နှင့် ဝန်ဆောင် မှု များ ကို ကာကွယ် ခြင်း ပါဝင် သည် ။ ၎င်း တွင် လျှို့ဝှက် ချက် ၊ ဝင်ရောက် ကြည့်ရှု ခြင်း ၊ စောင့် ကြည့် ခြင်း နှင့် လုံခြုံ ရေး စံနှုန်း များ ကို လိုက်နာ ခြင်း ကဲ့သို့ အတိုင်းအတာ များ ပါဝင် သည် ။';
                break;
             case 'text7':
                textElement.textContent = 'အချက်အလက်လုံခြုံ ရေး တွင် အချက်အလက် များ နှင့် သတင်း အချက်အလက် စနစ် များ ကို ခွင့်ပြုချက် မ ရ ဘဲ ဝင်ရောက် ကြည့်ရှု ခြင်း ၊ ထုတ်ဖော် ပြောကြား ခြင်း ၊ ပြောင်းလဲ ခြင်း ၊ သို့မဟုတ် ဖျက်ဆီး ခြင်း မှ ကာကွယ် ခြင်း ပါဝင် သည် ။ ယင်း၏ရည်မှန်းချက်မှာ လျှို့ဝှက်ချက်၊ သမာဓိနှင့် သတင်းအချက်အလက်များရရှိနိုင်ရန် သေချာစေရန်ဖြစ်သည်။ အချက်အလက် လုံခြုံ ရေး ၊ သို့မဟုတ် InfoSec သည် ၊ ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု ၊ ထုတ်ဖော် ပြောကြား ခြင်း ၊ ပြောင်းလဲ ခြင်း နှင့် ဖျက်ဆီး ခြင်း တို့ မှ အချက်အလက် များ ကို ကာကွယ် ရန် ရည်ရွယ် ထား သော အလေ့အကျင့် များ နှင့် လုပ်ငန်းစဉ် များ ကို ရည်ညွှန်း သည် ။ ၎င်း သည် လျှို့ဝှက် ချက် ၊ သမာဓိ ၊ နှင့် ရရှိ နိုင် သော သတင်း အချက်အလက် များ ရရှိ နိုင် မှု ကို ထိန်းသိမ်း ခြင်း အပေါ် အာရုံစိုက် သည် ။ InfoSec တွင် ဆိုက်ဘာ ခြိမ်းခြောက် မှု များ ၊ အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် အခြား လုံခြုံ ရေး အန္တရာယ် များ မှ ကာကွယ် ရန် မတော်တဆ တုံ့ပြန် မှု များ ပါဝင် သည် ။ ယင်း၏ရည်ရွယ်ချက်မှာ ထိခိုက်လွယ်သော သတင်းအချက်အလက်များသည် စင်တာများနှင့် ပတ်ဝန်းကျင်အသီးသီးတွင် လုံခြုံပြီး ယုံကြည်စိတ်ချရကြောင်း သေချာစေရန်ဖြစ်သည်။ အချက်အလက် လုံခြုံ ရေး သည် ခွင့်ပြုချက် မ ရ သော အချက်အလက် များ နှင့် သတင်း အချက်အလက် စနစ် များ ကို ခွင့်ပြုချက် မ ရ ဘဲ ဝင်ရောက် ကြည့်ရှု ခြင်း ၊ အသုံးပြု ခြင်း ၊ ထုတ်ဖော် ပြောကြား ခြင်း ၊ အနှောင့်အယှက် ၊ ပြုပြင် ခြင်း ၊ ပြုပြင် ခြင်း ၊ ဖျက်ဆီး ခြင်း မှ ကာကွယ် ပေး သည့် အလေ့အကျင့် ဖြစ် သည် ။ အဓိကမူများတွင် လျှို့ဝှက်ချက် (ခွင့်ပြုချက်မရသေးသော အချက်အလက်များကို ကာကွယ်ပေးခြင်း) ၊ သမာဓိ (သတင်းအချက်အလက်များကို တိကျမှန်ကန်ပြီး ယုံကြည်စိတ်ချထိုက်ကြောင်း သေချာစေခြင်း)နှင့် ရရှိနိုင်စွမ်း (လိုအပ်သည့်အခါ သတင်းအချက်အလက်များရရှိနိုင်ရန် သေချာစေခြင်း)တို့ပါဝင်သည်။ ';
                break;
            case 'text8':
                textElement.textContent = 'မိုဘိုင်းလုံခြုံရေးသည် စမတ်ဖုန်း များ နှင့် တက်ဘလက် များ ကို မားလ်ဝဲ ၊ အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု ခြင်း ကဲ့သို့ ခြိမ်းခြောက် မှု များ မှ ကာကွယ် ခြင်း ကို ရည်ညွှန်း သည် ။ ၎င်း တွင် ခိုင်မာ သော စကားဝှက် များ အသုံးပြု ခြင်း ၊ ဆော့ဖ်ဝဲလ် ကို ခေတ်မီ အောင် ထိန်းသိမ်း ခြင်း ၊ နှင့် ထိခိုက်လွယ် သော သတင်း အချက်အလက် များ ကို ကာကွယ် ရန် နှင့် လုံခြုံ ရေး ကိရိယာ အသုံးပြု မှု သေချာ စေရန် လုံခြုံ ရေး apps များ ကို အသုံးပြု ခြင်း ကဲ့သို့ တိုင်းတာ မှု များ ပါဝင် သည် ။ မိုဘိုင်း လုံခြုံ ရေး တွင် စမတ်ဖုန်း များ ၊ တက်ဘလက် များ ၊ နှင့် အခြား သယ်ယူရလွယ်ကူ သော ကိရိယာ များ ကို မားလ်ဝဲ ၊ ခွင့်ပြု ချက် မ ရှိ ဝင်ရောက် ကြည့်ရှု ခြင်း ၊ အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် ဖစ်ရှင်း တိုက်ခိုက် မှု များ စ သည့် ခြိမ်းခြောက် မှု များ မှ ကာကွယ် ပေး ခြင်း ပါဝင် သည်။ ယင်းတွင် ခိုင်မာသော စကားဝှက်များကို အသုံးပြုခြင်း၊ လျှို့ဝှက်ချက်ပေးခြင်း၊ ဆော့ဖ်ဝဲလ် မှန်မှန်ပြင်ဆင်ခြင်း၊ လုံခြုံရေး apps များအသုံးပြုခြင်းတို့ပါဝင်ပြီး ခြိမ်းခြောက်မှုများကိုရှာဖွေကာ တားဆီးရန် လုံခြုံရေး apps များ အသုံးပြုခြင်းတို့ပါဝင်သည်။ မိုဘိုင်း လုံခြုံ ရေး သည် လည်း ကွန်ယက် ပေါ်တွင် ထုတ် လွှင့် သော ထိခိုက်လွယ် သော အချက်အလက် များ ကို ကာကွယ် စောင့်ရှောက် ခြင်း ၊ app ခွင့်ပြုချက် များ ကို စီမံ ခန့်ခွဲ ခြင်း ၊ နှင့် လုံခြုံ သော ဆက်သွယ် မှု များ သေချာ စေ ခြင်း တို့ ပါဝင် သည် ။ ယင်း၏ရည်ရွယ်ချက်မှာ မိုဘိုင်းလ်ကိရိယာများပေါ်ရှိ ကိုယ်ရေးကိုယ်တာနှင့် ကော်ပိုရေးရှင်း အချက်အလက်များကို ကာကွယ်ရန်ဖြစ်ပြီး ကိုယ်ရေးကိုယ်တာနှင့် ကျွမ်းကျင်မှုနှစ်ရပ်စလုံးတွင် သီးသန့်နေရေးနှင့် လုံခြုံရေးကို သေချာစေရန်ဖြစ်သည်။ မိုဘိုင်း လုံခြုံ ရေး တွင် မော်လ်ဝဲ ၊ အချက်အလက် ချိုးဖောက် မှု များ နှင့် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု များ ကဲ့သို့ ခြိမ်းခြောက် မှု များ မှ မိုဘိုင်း ကိရိယာ များ ကို ကာကွယ် ခြင်း ပါဝင် သည် ။ အဓိကဒြပ်စင်များတွင် ခိုင်မာသော စကားဝှက်များကို အသုံးပြုခြင်း၊ အချက်နှစ်ချက် စစ်ဆေးခြင်း၊ ဆော့ဖ်ဝဲလ်ကို အသစ်ပြင်ဆင်ထားခြင်း၊ ယုံကြည်စိတ်ချမှုမရှိသော apps များနှင့် ကွန်ရက်များကို ရှောင်ကြဉ်ခြင်းတို့ပါဝင်သည်။ ဤလုပ်ဆောင်မှုများက ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ကာကွယ်စောင့်ရှောက်ပေးပြီး ကိရိယာလုံခြုံမှုကို သေချာစေသည်။';
                break;
        }
        buttonElement.textContent = 'Translate to English';
    } else {
        // Translate to English
        switch(textId) {
            case 'text1':
                textElement.textContent = 'Artificial Intelligence(AI) improves security by enhancing threat detection, response capabilities, and overall cybersecurity measures in the following ways: Advanced Threat Detection and Real-time Monitoring: AI analyzes data for unusual patterns and behaviors, enabling early threat detection.AI security refers to the measures and practices designed to protect artificial intelligence systems from threats and vulnerabilities. It involves safeguarding AI models and data from misuse, attacks, and unauthorized access to ensure they operate safely and ethically. Key concerns include ensuring data privacy, preventing model manipulation, and protecting against adversarial attacks.This overview focuses on the definition of AI security, which involves using AI to improve cybersecurity. However, it also includes information on AI\'s potential vulnerabilities and best practices for protecting AI systems. Artificial intelligence (AI) has revolutionized various industries, and cybersecurity is no exception. AI security solutions have emerged as powerful tools for identifying and mitigating potential threats in today\'s digital landscape.';
                break;
            case 'text2':
                textElement.textContent = 'Critical infrastructure security involves safeguarding essential systems and assets, such as utilities and transportation networks, from threats to ensure their continuous operation and protect public safety. Critical infrastructure security involves protecting essential systems and assets that are vital to national security, economy, and public safety from threats and disruptions. Critical infrastructure cybersecurity protects essential systems like energy, water, and Compliance with regulations is crucial for maintaining security. The goal is to ensure these vital services remain operational and secure. It ensures that the critical infrastructures of organizations in industries like agriculture, energy, food, and transportation receive protection against cyber threats, natural disasters, and terrorist threats.Access Control: The prevention of unauthorized users and devices from accessing the network. Application Security: Security measures are placed on hardware and software to lock down potential vulnerabilities. Firewalls: Gatekeeping devices that can allow or prevent specific traffic from entering or leaving the network.';
                break;
            case 'text3':
                textElement.textContent = 'Network security is the protection of the underlying networking infrastructure from unauthorized access, misuse, or theft.It involves creating a secure infrastructure for devices, applications, users, and applications to work in a secure manner. Network security involves protecting a computer network and its data from unauthorized access, misuse, and cyberattacks. It includes measures such as firewalls, encryption, intrusion detection systems, and regular monitoring to ensure the integrity, confidentiality, and availability of network resources. Network security is essential for safeguarding digital infrastructure, ensuring data integrity, confidentiality, and availability. It involves implementing firewalls, intrusion detection systems, and encryption to protect against unauthorized access and cyber threats. Access control and secure authentication help regulate network resource usage, while continuous monitoring and regular updates are crucial for identifying and mitigating vulnerabilities. In an era of evolving cyber threats, robust network security is vital for protecting sensitive information and maintaining trust in digital communications. Network Security protects your network and data from breaches, intrusions and other threats. This is a vast and overarching term that describes hardware and software solutions as well as processes or rules and configurations relating to network use, accessibility, and overall threat protection.Network Security involves access control, virus and antivirus software, application security, network analytics, types of network-related security (endpoint, web, wireless), firewalls, VPN encryption and more.';
                break;
            case 'text4':
                textElement.textContent = "Endpoint security refers to the protection of individual devices, such as computers, smartphones, and tablets, from cyber threats. It involves implementing security measures like antivirus software, firewalls, and encryption to safeguard these devices from potential attacks and unauthorized access. Endpoint security refers to the practice of protecting devices like computers, smartphones, and tablets that connect to a network. It involves implementing security measures to prevent threats such as malware, unauthorized access, and data breaches on these devices. Endpoint security solutions often include antivirus software, firewalls, intrusion detection systems, and encryption to safeguard both the devices and the network they connect to. The goal is to ensure that endpoints are secure, reducing the risk of security incidents that could compromise the entire network. An endpoint protection platform (EPP) is a solution used to detect and prevent security threats like file-based malware attacks among other malicious activities. It also provides investigation and remediation capabilities needed to respond to dynamic security incidents and alerts";
                break;
            case 'text5':
                textElement.textContent = 'Application security involves measures and practices designed to protect applications from threats and vulnerabilities. It focuses on securing software and its data throughout its lifecycle, ensuring that applications are protected against attacks and unauthorized access. Application security involves protecting software applications from threats and vulnerabilities. It includes measures like code reviews, penetration testing, and secure coding practices to ensure the application is secure from attacks and unauthorized access throughout its lifecycle. The ultimate goal of application security is to prevent attackers from accessing, modifying or deleting sensitive or proprietary data. The most common application security weaknesses are well-known. Various organizations track them over time. The Open Web Application Security Project (OWASP) Top Ten list and the Common Weakness Enumeration (CWE) compiled by the information security community are two of the best-known lists of application weaknesses.Application security involves protecting software applications from threats and vulnerabilities that could lead to unauthorized access, data breaches, or other malicious activities. It includes practices such as secure coding, regular testing for vulnerabilities, implementing authentication and authorization mechanisms, and maintaining software updates.';
                break;
            case 'text6':
                textElement.textContent = 'Cloud security involves protecting data, applications, and services hosted on cloud platforms from various threats. It includes measures such as encryption, access control, and regular monitoring to ensure the confidentiality, integrity, and availability of cloud-based resources. Cloud security involves the policies, technologies, and controls implemented to protect data, applications, and infrastructure within cloud computing environments. It focuses on ensuring data privacy, integrity, and availability by protecting against unauthorized access, data breaches, and other cyber threats. Key aspects include data encryption, identity and access management, compliance with regulations, network security, and monitoring for threats and vulnerabilities. Cloud security is crucial for businesses to safeguard sensitive information and maintain trust in their cloud services. Cloud security involves protecting data, applications, and services stored in cloud environments from threats such as unauthorized access, data breaches, and cyberattacks. It includes measures like encryption, access controls, monitoring, and compliance with security standards to ensure the confidentiality, integrity, and availability of cloud resources.';
                break;
            case 'text7':
                textElement.textContent = 'Information security involves protecting data and information systems from unauthorized access, disclosure, alteration, or destruction. Its goal is to ensure confidentiality, integrity, and availability of information. Information security, or InfoSec, refers to the practices and processes designed to protect data from unauthorized access, disclosure, alteration, and destruction. It focuses on preserving the confidentiality, integrity, and availability of information, whether it\'s stored, processed, or transmitted. InfoSec includes measures like access control, encryption, threat detection, and incident response to protect against cyber threats, data breaches, and other security risks. Its goal is to ensure that sensitive information remains secure and reliable across various platforms and environments. Information security is the practice of protecting data and information systems from unauthorized access, use, disclosure, disruption, modification, or destruction. Key principles include confidentiality (protecting information from unauthorized access), integrity (ensuring information is accurate and trustworthy), and availability (ensuring information is accessible when needed).';
                break;
            case 'text8':
                textElement.textContent = 'Mobile security refers to the protection of smartphones and tablets from threats such as malware, data breaches, and unauthorized access. It involves measures like using strong passwords, keeping software up to date, and employing security apps to safeguard sensitive information and ensure safe device usage. Mobile security involves protecting smartphones, tablets, and other portable devices from threats such as malware, unauthorized access, data breaches, and phishing attacks. It includes practices like using strong passwords, enabling encryption, regularly updating software, and using security apps to detect and prevent threats. Mobile security also covers safeguarding sensitive data transmitted over networks, managing app permissions, and ensuring secure connections. Its goal is to protect personal and corporate data on mobile devices, ensuring privacy and security in both personal and professional use. Mobile security involves protecting mobile devices from threats like malware, data breaches, and unauthorized access. Key elements include using strong passwords, enabling two-factor authentication, keeping software updated, and avoiding untrusted apps and networks. These measures help safeguard personal information and ensure device security.';
                break;
        }
        buttonElement.textContent = 'Translate to Myanmar';
    }
}










// let isEnglish = true;

// function Translation() {
//     const p1 = document.getElementById('p1');
//     const p2 = document.getElementById('p2');
//     const p3 = document.getElementById('p3');
//     const p4 = document.getElementById('p4');
//     const p5 = document.getElementById('p5');
//     const p6 = document.getElementById('p6');
//     const p7 = document.getElementById('p7');
//     const p8 = document.getElementById('p8');
//     const buttonElement = document.getElementById('translateButton');

//     if (isEnglish) {
//         // Translate both paragraphs to Myanmar
//         p1.textContent = "အတုအယောင် ထောက်လှမ်းရေး (AI) သည် ခြိမ်းခြောက်မှု ရှာဖွေတွေ့ရှိမှုကို တိုးမြှင့်ခြင်းဖြင့် လုံခြုံမှုကို တိုးတက်စေပြီး တုံ့ပြန်နိုင်စွမ်းများနှင့် အောက်ပါနည်းများဖြင့် ဆိုက်ဘာလုံခြုံရေး တိုင်းတာချက်များ– အဆင့်မြင့်ခြိမ်းခြောက်မှု ရှာဖွေတွေ့ရှိခြင်းနှင့် အချိန်မှန်စောင့်ကြည့်ခြင်း: AI သည် ထူးခြားသော ပုံစံများနှင့် အပြုအမူများအတွက် အချက်အလက်များကို ဆန်းစစ်ပြီး စောစောခြိမ်းခြောက်မှုကို ရှာဖွေတွေ့ရှိနိုင်သည်။ အေအိုင် လုံခြုံ ရေး သည် ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ မှ ဉာဏ်ရည်တု စနစ် များ ကို ကာကွယ် ရန် ရည်ရွယ် ထား သော ဆောင်ရွက် ချက် များ နှင့် အလေ့အကျင့် များ ကို ရည်ညွှန်း သည် ။ ယင်း တွင် အေအိုင် မော်ဒယ် များ နှင့် အချက်အလက် များ ကို အလွဲသုံးစား ပြု ခြင်း ၊ တိုက်ခိုက် မှု များ ၊ နှင့် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု များ မှ ကာကွယ် စောင့်ရှောက် ခြင်း ပါဝင် သည် ။ အဓိက စိုးရိမ် ပူပန် မှု များ တွင် အချက်အလက် လုံခြုံ ရေး သေချာ စေ ခြင်း ၊ ပုံစံ ကို ထိန်းချုပ် ခြင်း ၊ နှင့် ရန်ဘက် တိုက်ခိုက် မှု များ ကို ကာကွယ် ခြင်း တို့ ပါဝင် သည် ။ ဤ ခြုံငုံ သုံးသပ် ချက် သည် ဆိုင်ဘာ ဘေးကင်း လုံခြုံ ရေး တိုးတက် ရန် အေအိုင် အသုံးပြု ခြင်း ပါဝင် သော ၊ အေအိုင် လုံခြုံ ရေး ၏ သတ်မှတ် ချက် အပေါ် အာရုံစိုက် သည် ။ သို့သော်လည်း ၊ ၎င်း သည် အေအိုင် ၏ အလားအလာ ရှိ သော အားနည်းချက် များ နှင့် အေအိုင် စနစ် များ ကို ကာကွယ် ရန် အ ကောင်း ဆုံး အလေ့အကျင့် များ အပေါ် သတင်း အချက်အလက် များ လည်း ပါဝင် သည် ။ အသိဉာဏ်အတု (AI) သည် စက်မှုလုပ်ငန်းအမျိုးမျိုးကို တော်လှန်ရေး လုပ်ကိုင်ခဲ့ပြီး ဆိုင်ဘာဘေးကင်းရေးမှာလည်း ခြွင်းချက်မရှိပါ။ အေအိုင် လုံခြုံ ရေး ဖြေရှင်း ချက် များ သည် ယနေ့ ၏ ဒစ်ဂျစ်တယ် ရှုခင်း တွင် ဖြစ် နိုင် ချေ ရှိ သော ခြိမ်းခြောက် မှု များ ကို ဖော် ထုတ် ရန် နှင့် လျှော့ချ ခြင်း အတွက် အစွမ်းထက် သော ကိရိယာ များ အဖြစ် ပေါ် ထွက် လာ ခဲ့ သည် ။";
//         p2.textContent = "အရေးကြီး သော အခြေခံ အဆောက်အအုံ လုံခြုံ ရေး တွင် ဝန်ဆောင် မှု များ နှင့် သယ်ယူ ပို့ဆောင် ရေး ကွန်ယက် များ ကဲ့သို့ ၊ မရှိမဖြစ် လိုအပ် သော စနစ် များ နှင့် ပိုင်ဆိုင် မှု များ ကို ကာကွယ် စောင့်ရှောက် ခြင်း ပါဝင် သည် ၊ သူ တို့ ၏ အဆက်မပြတ် လုပ်ဆောင် မှု ကို သေချာ စေရန် နှင့် ပြည်သူ့ လုံခြုံ ရေး ကို ကာကွယ် ရန် ခြိမ်းခြောက် မှု များ မှ ပါဝင် သည် ။ အရေးကြီး သော အခြေခံ အဆောက်အအုံ လုံခြုံ ရေး တွင် အမျိုးသား လုံခြုံ ရေး ၊ စီးပွားရေး ၊ နှင့် ပြည်သူ့ လုံခြုံ ရေး အတွက် အရေးပါ သော မရှိမဖြစ် လိုအပ် သော စနစ် များ နှင့် ပိုင်ဆိုင် မှု များ ကို ကာကွယ် ခြင်း ပါဝင် သည် ။ အရေးပါသော အခြေခံအဆောက်အအုံများ လုံခြုံရေးသည် စွမ်းအင်၊ ရေနှင့် လိုက်နာမှုကဲ့သို့သော မရှိမဖြစ်လိုအပ်သောစနစ်များကို ကာကွယ်ပေးသည်။ လုံခြုံရေးထိန်းသိမ်းရေးအတွက် အရေးပါသည်။ ရည်ရွယ် ချက် မှာ ဤ အရေးကြီး သော ဝန်ဆောင် မှု များ လုပ်ဆောင် မှု နှင့် လုံခြုံ မှု ကို သေချာ စေရန် ဖြစ် သည် ။ စိုက်ပျိုးရေး၊ စွမ်းအင်၊ အစားအစာနှင့် သယ်ယူပို့ဆောင်ရေးကဲ့သို့သော စက်မှုလုပ်ငန်းများတွင် အဖွဲ့အစည်းများ၏ အရေးပါသော အခြေခံအဆောက်အအုံများသည် ဆိုက်ဘာခြိမ်းခြောက်မှုများ၊ သဘာဝဘေးအန္တရာယ်များနှင့် အကြမ်းဖက်ခြိမ်းခြောက်မှုများမှ ကာကွယ်မှုရရှိရန် သေချာစေသည်။ ဝင်ရောက်ကြည့်ရှုရေး ထိန်းချုပ်မှု– ခွင့်ပြုချက်မရတဲ့ အသုံးပြုသူတွေနဲ့ ကိရိယာတွေကို တားဆီးခြင်းက ကွန်ယက်ကို ဝင်ရောက်ကြည့်ရှုခြင်းမှ ကာကွယ်ခြင်း။  Application လုံခြုံရေး – လုံခြုံ ရေး ဆောင်ရွက် ချက် များ ကို ဖြစ် နိုင် ချေ ရှိ သော အားနည်းချက် များ ကို ပိတ်ဆို့ ရန် ဟာ့ဒ်ဝဲ နှင့် ဆော့ဖ်ဝဲလ် များ တွင် ထား ရှိ သည် ။ မီးရှူးမီးပန်းများ– ယာဉ်အသွားအလာကို ကွန်ရက်ထဲဝင်ခြင်း သို့မဟုတ် ထွက်ခွာခြင်းမှ တားဆီးနိုင်သည့် သို့မဟုတ် တားဆီးနိုင်သည့် ဂိတ်ကီပင်းကိရိယာများ";
//         p3.textContent = "Network security ဆိုသည်မှာ အခြေခံကွန်ရက်အခြေခံအဆောက်အအုံကို ခွင့်ပြုမထားသော လှမ်းလာခြင်း၊ မဖြစ်သင့်သောအသုံးချခြင်း၊ သို့မဟုတ် ခိုးယူမှုမှ ကာကွယ်ပေးခြင်းဖြစ်သည်။ ဤသည်မှာ ကိရိယာများ၊ အက်ပ်လီကေးရှင်းများ၊ အသုံးပြုသူများနှင့် အက်ပ်လီကေးရှင်းများကို လုံခြုံစွာ လုပ်ဆောင်နိုင်ရန် အဆောက်အအုံတည်ဆောက်ခြင်းနှင့် ပတ်သက်ပြီးပါသည်။ Network security ဆိုသည်မှာ ကွန်ပျူတာကွန်ရက်နှင့် ၎င်း၏ဒေတာများကို ခွင့်ပြုမထားသော လှမ်းလာခြင်း၊ မဖြစ်သင့်သောအသုံးချခြင်း၊ နှင့် စက်မှုကျူးလွန်မှုများမှ ကာကွယ်ပေးခြင်းဖြစ်သည်။၎င်းတွင် ဖိုင်ဝေါ်များ၊ စာဝှက်ခြင်း၊ intrusion detection systems (IDS) နှင့် ကွန်ရက်ရင်းမြစ်များ၏ စိစစ်မှု၊ လျှို့ဝှက်မှု၊ နောက်ဆုံးအခြေအနေအတိုင်းရှိမှုတို့ကို သေချာစေရန် ပုံမှန်ကြီးကြပ်မှုတို့ကို လုပ်ဆောင်ပါသည်။ စက်မှုကျူးလွန်မှုများထပ်မံဖြစ်ပေါ်လာသောခေတ်တစ်ခေတ်တွင် ခိုင်မာသောကွန်ရက်လုံခြုံရေးသည် အရေးကြီးသောသတင်းအချက်အလက်များကို ကာကွယ်ရန်နှင့် ဒစ်ဂျစ်တယ်ဆက်သွယ်ရေးတွင် ယုံကြည်မှုကို ထိန်းသိမ်းထားရန် အရေးကြီးသည်။ ကွန်ယက် လုံခြုံ ရေး သည် သင် ၏ ကွန်ရက် နှင့် အချက်အလက် များ ကို ချိုးဖောက် မှု များ ၊ ဝင်ရောက် ဝင်ရောက် စွက်ဖက် မှု များ နှင့် အခြား ခြိမ်းခြောက် မှု များ မှ ကာကွယ် ပေး သည် ။ ၎င်း သည် ဟာ့ဒ်ဝဲ နှင့် ဆော့ဖ်ဝဲလ် ဖြေရှင်းနည်း များ အပြင် ကွန်ယက် အသုံးပြု မှု ၊ ဝင်ရောက် ကြည့်ရှု နိုင် မှု ၊ နှင့် ခြုံငုံ ခြိမ်းခြောက် မှု ကာကွယ်ရေး နှင့် ဆက်စပ် သော လုပ်ငန်းစဉ် များ သို့မဟုတ် စည်းမျဉ်း များ နှင့် ဖွဲ့စည်းပုံ များ ကို ဖော်ပြ သော ကြီးမား ကျယ်ပြန့် ပြီး အလွန် ကြီးမား သော အသုံးအနှုန်း တစ် ခု ဖြစ် သည် ။ ကွန်ယက် လုံခြုံ ရေး တွင် ထိန်းချုပ် မှု ၊ ဗိုင်းရပ်စ် နှင့် အန်တီဗိုင်းရပ်စ် ဆော့ဖ်ဝဲလ် ၊ application လုံခြုံ ရေး ၊ ကွန်ယက် ခွဲခြမ်းစိတ်ဖြာ မှု ၊ ကွန်ယက် နှင့် ဆက်စပ် သော လုံခြုံ ရေး အမျိုးအစား များ ( အဆုံးသတ် နေရာ ၊ ကြိုးမဲ့ဆက်သွယ်ရေး ၊ ဗီပီအန် လျှို့ဝှက် မှု နှင့် ပိုမို ပါဝင် သည် ။";
//         p4.textContent = "Endpoint security ဆိုသည်မှာ ကွန်ရက်လမ်းကြောင်းများအတိုင်း ကွန်ပျူတာ၊ စမတ်ဖုန်းများနှင့် တက်ဘလက်များကဲ့သို့သော တစ်ဦးချင်းစီ၏ ကိရိယာများကို စက်မှုကျူးလွန်မှုများမှ ကာကွယ်ခြင်းဖြစ်သည်။ ဤကိရိယာများကို အန္တရာယ်ဖြစ်နိုင်မှုများနှင့် ခွင့်ပြုမထားသော လှမ်းလာမှုများမှ ကာကွယ်ရန် ဗိုင်းရပ်စ်ဘက်စုံကာကွယ်ရေးဆော့ဖ်ဝဲ၊ ဖိုင်ဝေါ်များနှင့် စာဝှက်ခြင်းကဲ့သို့သော လုံခြုံရေးအတိုင်းအတာများကို ပြုလုပ်ခြင်းဖြစ်သည်။ Endpoint security ဆိုသည်မှာ ကွန်ရက်သို့ ချိတ်ဆက်ထားသော ကွန်ပျူတာများ၊ စမတ်ဖုန်းများနှင့် တက်ဘလက်များကဲ့သို့သော ကိရိယာများကို ကာကွယ်ရန် လုံခြုံရေးအတိုင်းအတာများကို လုပ်ဆောင်ခြင်းဖြစ်သည်။ ကိရိယာများနှင့် ၎င်းတို့ချိတ်ဆက်ထားသောကွန်ရက်ကို ကာကွယ်ရန် ဗိုင်းရပ်စ်ဘက်စုံကာကွယ်ရေးဆော့ဖ်ဝဲ၊ ဖိုင်ဝေါ်များ၊ intrusion detection systems (IDS) နှင့် စာဝှက်ခြင်းကို လုံခြုံရေးဖြေရှင်းချက်များသည် လက်ရှိဖြစ်စဉ်ဖြစ်သည်။ ကိရိယာများကို လုံခြုံစေရန်အတွက် ရည်ရွယ်ချက်မှာ ကွန်ရက်၏လုံခြုံရေးဖြစ်ရပ်များကို လျော့နည်းစေခြင်းဖြစ်သည်။ အဆုံးသတ် ကာကွယ်ရေး စင်တာ ( အီးပီပီ ) သည် အခြား မလိုမုန်းထား သော လုပ်ဆောင် မှု များ အကြား ဖိုင် - အခြေပြု မားလ်ဝဲ တိုက်ခိုက် မှု များ ကဲ့သို့ လုံခြုံ ရေး ခြိမ်းခြောက် မှု များ ကို ဖော် ထုတ် ရန် နှင့် ကာကွယ် ရန် အသုံးပြု သော ဖြေရှင်း ချက် တစ် ခု ဖြစ် သည် ။ ၎င်း သည် ပြင်းထန် သော လုံခြုံ ရေး ဖြစ်ရပ် များ နှင့် သတိပေးချက် များ ကို တုံ့ပြန် ရန် လိုအပ် သော စုံစမ်း စစ်ဆေး မှု နှင့် ပြန်လည် ပြုပြင် ရေး စွမ်းရည် များ ကို လည်း ထောက်ပံ့ ပေး သည်";
//         p5.textContent = "လျှောက်လွှာ လုံခြုံ ရေး တွင် လျှောက်လွှာ များ ကို ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ မှ ကာကွယ် ရန် ရည်ရွယ် ထား သော တိုင်းတာ မှု များ နှင့် အလေ့အကျင့် များ ပါဝင် သည် ။  ၎င်း သည် ဆော့ဖ်ဝဲလ် နှင့် ၎င်း ၏ အချက်အလက် များ ကို ၎င်း ၏ သက်တမ်း တစ်လျှောက် လုံး လုံခြုံ ရေး အပေါ် အာရုံစိုက် ပြီး ၊ အပလီကေးရှင်း များ ကို တိုက်ခိုက် မှု များ နှင့် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု များ မှ ကာကွယ် ပေး ရန် သေချာ စေ သည် ။ Application လုံခြုံ ရေး တွင် ဆော့ဖ်ဝဲလ် ပရိုဂရိတ် များ ကို ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ မှ ကာကွယ် ခြင်း ပါဝင် သည် ။ ၎င်း တွင် တိုက်ခိုက် မှု များ မှ လျှောက်လွှာ လုံခြုံ မှု ရှိ စေရန် နှင့် ၎င်း ၏ သက်တမ်း တစ်လျှောက် လုံး ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု များ မှ လုံခြုံ မှု ရှိ စေရန် သေချာ စေရန် ကုဒ် သုံးသပ် မှု များ ၊ ထိုးဖောက် ခြင်း စမ်းသပ် ခြင်း ၊ နှင့် လုံခြုံ သော ကုဒ် လုပ်ထုံးလုပ်နည်း များ ပါဝင် သည် ။ လျှောက်လွှာ လုံခြုံ ရေး ၏ အဆုံးသတ် ရည်မှန်း ချက် မှာ တိုက်ခိုက် သူ များ ကို ထိခိုက်လွယ် သော သို့မဟုတ် ပိုင်ဆိုင် သော အချက်အလက် များ ကို ဖျက် ခြင်း မှ ကာကွယ် ရန် ဖြစ် သည် ။ အသုံးချမှုအများဆုံး လုံခြုံရေးအားနည်းချက်များကို လူသိများကြသည်။ အချိန်ကြာလာတာနဲ့အမျှ အဖွဲ့အစည်းအသီးသီးက ခြေရာခံကြတယ်။ အိုးပင်းဝက်ဘ်အပ္ပလီကေးရှင်း လုံခြုံရေး စီမံကိန်း (အိုးဒဗလျူအေအက်စ်ပီ) ထိပ်တန်း ဆယ်ခုစာရင်းနှင့် သာမန် အားနည်းချက်များ အန်ဒဗလျူအီး) ပေါင်းစပ်ပါသည်။ Application လုံခြုံ ရေး တွင် ဆော့ဖ်ဝဲလ် ပရိုဂရမ် များ ကို ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ မှ ကာကွယ် ခြင်း ပါဝင် ပြီး ခွင့်ပြု ချက် မ ရှိ သော အချက်အလက် ချိုးဖောက် မှု များ ၊ သို့မဟုတ် အခြား မလိုတမာ လုပ်ဆောင် မှု များ ကို ဦးတည် စေ နိုင် သည် ။ ၎င်း တွင် လုံခြုံ သော ကိုဒင်း ပြုလုပ် ခြင်း ၊ အားနည်းချက် များ အတွက် ပုံမှန် စမ်းသပ် ခြင်း ၊ စစ်ဆေး ခြင်း နှင့် ခွင့်ပြု ချက် စနစ် များ အကောင်အထည်ဖော် ခြင်း ၊ နှင့် ဆော့ဖ်ဝဲလ် အသစ် ပြင်ဆင် မှု များ ကို ထိန်းသိမ်း ခြင်း ကဲ့သို့ အလေ့အကျင့် များ ပါဝင် သည် ။";
//         p6.textContent = "Cloud security တွင် အချက်အလက် များ ၊ application များ ၊ နှင့် ဝန်ဆောင် မှု များ ကို ကာကွယ် ခြင်း ပါဝင် သည် ။ ၎င်း တွင် လျှို့ဝှက် ချက် ၊ ဝင်ရောက် ကြည့်ရှု မှု ထိန်းချုပ် ခြင်း ၊ ပုံမှန် စောင့် ကြည့် ခြင်း စ သည့် ဆောင်ရွက် ချက် များ ပါဝင် ပြီး တိမ် - အခြေပြု အရင်းအမြစ် များ ရရှိ နိုင် မှု ကို သေချာ စေရန် လျှို့ဝှက် ချက် ၊ အစုလိုက်အပြုံလိုက် လုံခြုံ ရေး တွင် အချက်အလက် များ ၊ ပရိုဂရမ် များ ၊ နှင့် အခြေခံ အဆောက်အအုံ များ ကို ကာကွယ် ရန် အကောင်အထည်ဖော် ထား သော မူဝါဒ များ ၊ နည်းပညာ များ ၊ နှင့် ထိန်းချုပ် မှု များ ပါဝင် သည် ။ ၎င်း သည် ခွင့်ပြုချက် မ ရှိ သော အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် အခြား ဆိုက်ဘာ ခြိမ်းခြောက် မှု များ မှ ကာကွယ် ခြင်း အားဖြင့် အချက်အလက် လုံခြုံ မှု ၊ သမာဓိ နှင့် ရရှိ နိုင် မှု ကို သေချာ စေရန် အာရုံစိုက် သည် ။ အဓိက ကဏ္ဍ များ တွင် အချက်အလက် လျှို့ဝှက် ခြင်း ၊ ကိုယ်ရေးကိုယ်တာ နှင့် ဝင်ရောက် ကြည့်ရှု မှု စီမံ ခန့်ခွဲ ခြင်း ၊ စည်းမျဉ်း များ ကို လိုက်နာ ခြင်း ၊ ကွန်ယက် လုံခြုံ ရေး ၊ နှင့် ခြိမ်းခြောက် မှု များ နှင့် အားနည်းချက် များ အတွက် စောင့် ကြည့် ခြင်း တို့ ပါဝင် သည် ။ Cloud security တွင် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု ၊ အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် ဆိုက်ဘာ တိုက်ခိုက် မှု များ ကဲ့သို့ ခြိမ်းခြောက် မှု များ မှ တိမ် ပတ်ဝန်းကျင် တွင် သိမ်းဆည်း ထား သော အချက်အလက် များ ၊ ပရိုဂရမ် များ ၊ နှင့် ဝန်ဆောင် မှု များ ကို ကာကွယ် ခြင်း ပါဝင် သည် ။ ၎င်း တွင် လျှို့ဝှက် ချက် ၊ ဝင်ရောက် ကြည့်ရှု ခြင်း ၊ စောင့် ကြည့် ခြင်း နှင့် လုံခြုံ ရေး စံနှုန်း များ ကို လိုက်နာ ခြင်း ကဲ့သို့ အတိုင်းအတာ များ ပါဝင် သည် ။";
//         p7.textContent = "အချက်အလက် လုံခြုံ ရေး တွင် အချက်အလက် များ နှင့် သတင်း အချက်အလက် စနစ် များ ကို ခွင့်ပြုချက် မ ရ ဘဲ ဝင်ရောက် ကြည့်ရှု ခြင်း ၊ ထုတ်ဖော် ပြောကြား ခြင်း ၊ ပြောင်းလဲ ခြင်း ၊ သို့မဟုတ် ဖျက်ဆီး ခြင်း မှ ကာကွယ် ခြင်း ပါဝင် သည် ။ ယင်း၏ရည်မှန်းချက်မှာ လျှို့ဝှက်ချက်၊ သမာဓိနှင့် သတင်းအချက်အလက်များရရှိနိုင်ရန် သေချာစေရန်ဖြစ်သည်။ အချက်အလက် လုံခြုံ ရေး ၊ သို့မဟုတ် InfoSec သည် ၊ ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု ၊ ထုတ်ဖော် ပြောကြား ခြင်း ၊ ပြောင်းလဲ ခြင်း နှင့် ဖျက်ဆီး ခြင်း တို့ မှ အချက်အလက် များ ကို ကာကွယ် ရန် ရည်ရွယ် ထား သော အလေ့အကျင့် များ နှင့် လုပ်ငန်းစဉ် များ ကို ရည်ညွှန်း သည် ။ ၎င်း သည် လျှို့ဝှက် ချက် ၊ သမာဓိ ၊ နှင့် ရရှိ နိုင် သော သတင်း အချက်အလက် များ ရရှိ နိုင် မှု ကို ထိန်းသိမ်း ခြင်း အပေါ် အာရုံစိုက် သည် ။ InfoSec တွင် ဆိုက်ဘာ ခြိမ်းခြောက် မှု များ ၊ အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် အခြား လုံခြုံ ရေး အန္တရာယ် များ မှ ကာကွယ် ရန် မတော်တဆ တုံ့ပြန် မှု များ ပါဝင် သည် ။ ယင်း၏ရည်ရွယ်ချက်မှာ ထိခိုက်လွယ်သော သတင်းအချက်အလက်များသည် စင်တာများနှင့် ပတ်ဝန်းကျင်အသီးသီးတွင် လုံခြုံပြီး ယုံကြည်စိတ်ချရကြောင်း သေချာစေရန်ဖြစ်သည်။ အချက်အလက် လုံခြုံ ရေး သည် ခွင့်ပြုချက် မ ရ သော အချက်အလက် များ နှင့် သတင်း အချက်အလက် စနစ် များ ကို ခွင့်ပြုချက် မ ရ ဘဲ ဝင်ရောက် ကြည့်ရှု ခြင်း ၊ အသုံးပြု ခြင်း ၊ ထုတ်ဖော် ပြောကြား ခြင်း ၊ အနှောင့်အယှက် ၊ ပြုပြင် ခြင်း ၊ ပြုပြင် ခြင်း ၊ ဖျက်ဆီး ခြင်း မှ ကာကွယ် ပေး သည့် အလေ့အကျင့် ဖြစ် သည် ။ အဓိကမူများတွင် လျှို့ဝှက်ချက် (ခွင့်ပြုချက်မရသေးသော အချက်အလက်များကို ကာကွယ်ပေးခြင်း) ၊ သမာဓိ (သတင်းအချက်အလက်များကို တိကျမှန်ကန်ပြီး ယုံကြည်စိတ်ချထိုက်ကြောင်း သေချာစေခြင်း)နှင့် ရရှိနိုင်စွမ်း (လိုအပ်သည့်အခါ သတင်းအချက်အလက်များရရှိနိုင်ရန် သေချာစေခြင်း)တို့ပါဝင်သည်။ ";
//         p8.textContent = "Mobile security သည် စမတ်ဖုန်း များ နှင့် တက်ဘလက် များ ကို မားလ်ဝဲ ၊ အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု ခြင်း ကဲ့သို့ ခြိမ်းခြောက် မှု များ မှ ကာကွယ် ခြင်း ကို ရည်ညွှန်း သည် ။ ၎င်း တွင် ခိုင်မာ သော စကားဝှက် များ အသုံးပြု ခြင်း ၊ ဆော့ဖ်ဝဲလ် ကို ခေတ်မီ အောင် ထိန်းသိမ်း ခြင်း ၊ နှင့် ထိခိုက်လွယ် သော သတင်း အချက်အလက် များ ကို ကာကွယ် ရန် နှင့် လုံခြုံ ရေး ကိရိယာ အသုံးပြု မှု သေချာ စေရန် လုံခြုံ ရေး apps များ ကို အသုံးပြု ခြင်း ကဲ့သို့ တိုင်းတာ မှု များ ပါဝင် သည် ။ မိုဘိုင်း လုံခြုံ ရေး တွင် စမတ်ဖုန်း များ ၊ တက်ဘလက် များ ၊ နှင့် အခြား သယ်ယူရလွယ်ကူ သော ကိရိယာ များ ကို မားလ်ဝဲ ၊ ခွင့်ပြု ချက် မ ရှိ ဝင်ရောက် ကြည့်ရှု ခြင်း ၊ အချက်အလက် ချိုးဖောက် မှု များ ၊ နှင့် ဖစ်ရှင်း တိုက်ခိုက် မှု များ စ သည့် ခြိမ်းခြောက် မှု များ မှ ကာကွယ် ပေး ခြင်း ပါဝင် သည်။ ယင်းတွင် ခိုင်မာသော စကားဝှက်များကို အသုံးပြုခြင်း၊ လျှို့ဝှက်ချက်ပေးခြင်း၊ ဆော့ဖ်ဝဲလ် မှန်မှန်ပြင်ဆင်ခြင်း၊ လုံခြုံရေး apps များအသုံးပြုခြင်းတို့ပါဝင်ပြီး ခြိမ်းခြောက်မှုများကိုရှာဖွေကာ တားဆီးရန် လုံခြုံရေး apps များ အသုံးပြုခြင်းတို့ပါဝင်သည်။ မိုဘိုင်း လုံခြုံ ရေး သည် လည်း ကွန်ယက် ပေါ်တွင် ထုတ် လွှင့် သော ထိခိုက်လွယ် သော အချက်အလက် များ ကို ကာကွယ် စောင့်ရှောက် ခြင်း ၊ app ခွင့်ပြုချက် များ ကို စီမံ ခန့်ခွဲ ခြင်း ၊ နှင့် လုံခြုံ သော ဆက်သွယ် မှု များ သေချာ စေ ခြင်း တို့ ပါဝင် သည် ။ ယင်း၏ရည်ရွယ်ချက်မှာ မိုဘိုင်းလ်ကိရိယာများပေါ်ရှိ ကိုယ်ရေးကိုယ်တာနှင့် ကော်ပိုရေးရှင်း အချက်အလက်များကို ကာကွယ်ရန်ဖြစ်ပြီး ကိုယ်ရေးကိုယ်တာနှင့် ကျွမ်းကျင်မှုနှစ်ရပ်စလုံးတွင် သီးသန့်နေရေးနှင့် လုံခြုံရေးကို သေချာစေရန်ဖြစ်သည်။ မိုဘိုင်း လုံခြုံ ရေး တွင် မော်လ်ဝဲ ၊ အချက်အလက် ချိုးဖောက် မှု များ နှင့် ခွင့်ပြု ချက် မ ရှိ သော ဝင်ရောက် ကြည့်ရှု မှု များ ကဲ့သို့ ခြိမ်းခြောက် မှု များ မှ မိုဘိုင်း ကိရိယာ များ ကို ကာကွယ် ခြင်း ပါဝင် သည် ။ အဓိကဒြပ်စင်များတွင် ခိုင်မာသော စကားဝှက်များကို အသုံးပြုခြင်း၊ အချက်နှစ်ချက် စစ်ဆေးခြင်း၊ ဆော့ဖ်ဝဲလ်ကို အသစ်ပြင်ဆင်ထားခြင်း၊ ယုံကြည်စိတ်ချမှုမရှိသော apps များနှင့် ကွန်ရက်များကို ရှောင်ကြဉ်ခြင်းတို့ပါဝင်သည်။ ဤလုပ်ဆောင်မှုများက ကိုယ်ရေးကိုယ်တာအချက်အလက်များကို ကာကွယ်စောင့်ရှောက်ပေးပြီး ကိရိယာလုံခြုံမှုကို သေချာစေသည်။";
//         buttonElement.textContent = "Translate to English";
        
//     } else {
//         // Translate both paragraphs to English
//         p1.textContent = "Artificial Intelligence(AI) improves security by enhancing threat detection, response capabilities, and overall cybersecurity measures in the following ways: Advanced Threat Detection and Real-time Monitoring: AI analyzes data for unusual patterns and behaviors, enabling early threat detection.AI security refers to the measures and practices designed to protect artificial intelligence systems from threats and vulnerabilities. It involves safeguarding AI models and data from misuse, attacks, and unauthorized access to ensure they operate safely and ethically. Key concerns include ensuring data privacy, preventing model manipulation, and protecting against adversarial attacks.This overview focuses on the definition of AI security, which involves using AI to improve cybersecurity. However, it also includes information on AI's potential vulnerabilities and best practices for protecting AI systems. Artificial intelligence (AI) has revolutionized various industries, and cybersecurity is no exception. AI security solutions have emerged as powerful tools for identifying and mitigating potential threats in today's digital landscape.";
//         p2.textContent = "Critical infrastructure security involves safeguarding essential systems and assets, such as utilities and transportation networks, from threats to ensure their continuous operation and protect public safety. Critical infrastructure security involves protecting essential systems and assets that are vital to national security, economy, and public safety from threats and disruptions. Critical infrastructure cybersecurity protects essential systems like energy, water, and Compliance with regulations is crucial for maintaining security. The goal is to ensure these vital services remain operational and secure. It ensures that the critical infrastructures of organizations in industries like agriculture, energy, food, and transportation receive protection against cyber threats, natural disasters, and terrorist threats.Access Control: The prevention of unauthorized users and devices from accessing the network. Application Security: Security measures are placed on hardware and software to lock down potential vulnerabilities. Firewalls: Gatekeeping devices that can allow or prevent specific traffic from entering or leaving the network";
//         p3.textContent = "Network security is the protection of the underlying networking infrastructure from unauthorized access, misuse, or theft.It involves creating a secure infrastructure for devices, applications, users, and applications to work in a secure manner. Network security involves protecting a computer network and its data from unauthorized access, misuse, and cyberattacks. It includes measures such as firewalls, encryption, intrusion detection systems, and regular monitoring to ensure the integrity, confidentiality, and availability of network resources. Network security is essential for safeguarding digital infrastructure, ensuring data integrity, confidentiality, and availability. It involves implementing firewalls, intrusion detection systems, and encryption to protect against unauthorized access and cyber threats. Access control and secure authentication help regulate network resource usage, while continuous monitoring and regular updates are crucial for identifying and mitigating vulnerabilities. In an era of evolving cyber threats, robust network security is vital for protecting sensitive information and maintaining trust in digital communications. Network Security protects your network and data from breaches, intrusions and other threats. This is a vast and overarching term that describes hardware and software solutions as well as processes or rules and configurations relating to network use, accessibility, and overall threat protection.Network Security involves access control, virus and antivirus software, application security, network analytics, types of network-related security (endpoint, web, wireless), firewalls, VPN encryption and more.";
//         p4.textContent = "Endpoint security refers to the protection of individual devices, such as computers, smartphones, and tablets, from cyber threats. It involves implementing security measures like antivirus software, firewalls, and encryption to safeguard these devices from potential attacks and unauthorized access. Endpoint security refers to the practice of protecting devices like computers, smartphones, and tablets that connect to a network. It involves implementing security measures to prevent threats such as malware, unauthorized access, and data breaches on these devices. Endpoint security solutions often include antivirus software, firewalls, intrusion detection systems, and encryption to safeguard both the devices and the network they connect to. The goal is to ensure that endpoints are secure, reducing the risk of security incidents that could compromise the entire network. An endpoint protection platform (EPP) is a solution used to detect and prevent security threats like file-based malware attacks among other malicious activities. It also provides investigation and remediation capabilities needed to respond to dynamic security incidents and alerts";
//         p5.textContent = "Application security involves measures and practices designed to protect applications from threats and vulnerabilities. It focuses on securing software and its data throughout its lifecycle, ensuring that applications are protected against attacks and unauthorized access. Application security involves protecting software applications from threats and vulnerabilities. It includes measures like code reviews, penetration testing, and secure coding practices to ensure the application is secure from attacks and unauthorized access throughout its lifecycle. The ultimate goal of application security is to prevent attackers from accessing, modifying or deleting sensitive or proprietary data. The most common application security weaknesses are well-known. Various organizations track them over time. The Open Web Application Security Project (OWASP) Top Ten list and the Common Weakness Enumeration (CWE) compiled by the information security community are two of the best-known lists of application weaknesses.Application security involves protecting software applications from threats and vulnerabilities that could lead to unauthorized access, data breaches, or other malicious activities. It includes practices such as secure coding, regular testing for vulnerabilities, implementing authentication and authorization mechanisms, and maintaining software updates.";
//         p6.textContent = "Cloud security involves protecting data, applications, and services hosted on cloud platforms from various threats. It includes measures such as encryption, access control, and regular monitoring to ensure the confidentiality, integrity, and availability of cloud-based resources. Cloud security involves the policies, technologies, and controls implemented to protect data, applications, and infrastructure within cloud computing environments. It focuses on ensuring data privacy, integrity, and availability by protecting against unauthorized access, data breaches, and other cyber threats. Key aspects include data encryption, identity and access management, compliance with regulations, network security, and monitoring for threats and vulnerabilities. Cloud security is crucial for businesses to safeguard sensitive information and maintain trust in their cloud services. Cloud security involves protecting data, applications, and services stored in cloud environments from threats such as unauthorized access, data breaches, and cyberattacks. It includes measures like encryption, access controls, monitoring, and compliance with security standards to ensure the confidentiality, integrity, and availability of cloud resources.";
//         p7.textContent = "Information security involves protecting data and information systems from unauthorized access, disclosure, alteration, or destruction. Its goal is to ensure confidentiality, integrity, and availability of information. Information security, or InfoSec, refers to the practices and processes designed to protect data from unauthorized access, disclosure, alteration, and destruction. It focuses on preserving the confidentiality, integrity, and availability of information, whether it's stored, processed, or transmitted. InfoSec includes measures like access control, encryption, threat detection, and incident response to protect against cyber threats, data breaches, and other security risks. Its goal is to ensure that sensitive information remains secure and reliable across various platforms and environments. Information security is the practice of protecting data and information systems from unauthorized access, use, disclosure, disruption, modification, or destruction. Key principles include confidentiality (protecting information from unauthorized access), integrity (ensuring information is accurate and trustworthy), and availability (ensuring information is accessible when needed).";
//         p8.textContent = "Mobile security refers to the protection of smartphones and tablets from threats such as malware, data breaches, and unauthorized access. It involves measures like using strong passwords, keeping software up to date, and employing security apps to safeguard sensitive information and ensure safe device usage. Mobile security involves protecting smartphones, tablets, and other portable devices from threats such as malware, unauthorized access, data breaches, and phishing attacks. It includes practices like using strong passwords, enabling encryption, regularly updating software, and using security apps to detect and prevent threats. Mobile security also covers safeguarding sensitive data transmitted over networks, managing app permissions, and ensuring secure connections. Its goal is to protect personal and corporate data on mobile devices, ensuring privacy and security in both personal and professional use. Mobile security involves protecting mobile devices from threats like malware, data breaches, and unauthorized access. Key elements include using strong passwords, enabling two-factor authentication, keeping software updated, and avoiding untrusted apps and networks. These measures help safeguard personal information and ensure device security.";
//         buttonElement.textContent = "Translate to Myanmar";
//     }

//     // Toggle the language state
//     isEnglish = !isEnglish;
// }